name: play_phaser
version: 0.8.4+1
description:
  A Dart port for Phaser.js library.
author: playif <playif@gmail.com>
homepage: https://github.com/playif/play_phaser
dependencies:
  browser: ">=0.10.0+2 <0.11.0"
  uuid: ">=0.3.2 < 0.4.0"
  play_pixi: ">=0.9.4+3 < 0.10.0"


transformers:
- $dart2js:
    checked: false
    minify: true
    suppressWarnings: false
    suppressHints: false
    terse: false
    verbose: true