name: play_phaser
version: 0.10.3+1
description:
  A Dart port for Phaser.js library.
author: playif <playif@gmail.com>
homepage: https://github.com/playif/play_phaser
dependencies:
  browser: ">=0.10.0+2 <0.11.0"
  p2: any
  play_pixi: any


transformers:
- $dart2js:
    checked: false
    minify: false
    suppressWarnings: false
    suppressHints: false
    terse: false
    verbose: true